### ISSUE TITLE
"npm test" failed

### ISSUE THREAD

**Issue by ghost** [ethereum/ethereum-client-binaries#16]
```
user@user-VirtualBox:~/ethereum-client-binaries$ npm test

> ethereum-client-binaries@1.6.4 test /home/user/ethereum-client-binaries
> mocha --timeout 180000 --ui exports --reporter spec test/*.test.js



  checkAvailability.test.js
    tests
      ✓ no clients
      ✓ client not supported on architecture
      ✓ client not supported on platform
      ✓ unable to resolve binary
      1) sanity check failed
      2) sanity check passed
      3) sanity check is mandatory
      4) client config returned
      ✓ search additional folders

  config.test.js
    tests
      ✓ DefaultConfig
      ✓ no config given
      ✓ config override

  download.test.js
    tests
       ✓ no clients
      ✓ client not supported on architecture
      ✓ client not supported on platform
      ✓ download info not available
      ✓ download url not available
      ✓ download unpack command not available
      ✓ download fails
      ✓ unsupported archive type
      ✓ hash sha256 mismatch
      ✓ hash md5 mismatch
      ✓ url regex mismatch
      ✓ unpacks and verifies ok
      ✓ unpacked but no binary found
      ✓ unpacked but sanity check failed
      ✓ unpacked and set to required name
      ✓ unpacked updated version and copied over old version
      ✓ hash sha256 match
      ✓ hash md5 match
      custom unpack handler
        ✓ success
        ✓ fail

  logger.test.js
    tests
      ✓ nothing by default
test logging
      ✓ turn on and off
      ✓ must be valid logger


  31 passing (2s)
  4 failing

  1) checkAvailability.test.js tests sanity check failed:

      AssertionError: expected 'notFound' to deeply equal 'sanityCheckFail'
      + expected - actual

      -notFound
      +sanityCheckFail

      at Context.test.sanity check failed (test/checkAvailability.test.js:153:34                                                                                                                                                                                               )
      at test.sanity check failed.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) checkAvailability.test.js tests sanity check passed:
     AssertionError: expected false to be true
      at Context.test.sanity check passed (test/checkAvailability.test.js:188:36                                                                                                                                                                                               )
      at test.sanity check passed.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) checkAvailability.test.js tests sanity check is mandatory:

      AssertionError: expected 'notFound' to deeply equal 'sanityCheckFail'
      + expected - actual

      -notFound
      +sanityCheckFail

      at Context.test.sanity check is mandatory (test/checkAvailability.test.js:                                                                                                                                                                                               219:34)
      at test.sanity check is mandatory.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  4) checkAvailability.test.js tests client config returned:

      AssertionError: expected { Object (homepage, version, ...) } to deeply equ                                                                                                                                                                                               al { Object (homepage, version, ...) }
      + expected - actual

                 "good:test"
               ]
             }
           }
      +    "fullPath": "/home/user/ethereum-client-binaries/test/bin/maga"
           "url": "http://badgerbadgerbadger.com"
         }
         "foo": "bar"
         "homepage": "http://badgerbadgerbadger.com"
             }
           }
         }
         "state": {
      -    "available": false
      -    "failReason": "notFound"
      +    "available": true
         }
         "version": "1.0.0"
         "versionNotes": "http://badgerbadgerbadger.com"
       }

      at Context.test.client config returned (test/checkAvailability.test.js:255                                                                                                                                                                                               :17)
      at test.client config returned.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



npm ERR! Test failed.  See above for more details.
```

Any Ideas?

**Comment by evertonfraga** [comment]
Here's my test run. What is the OS of your VM? I am running on mac. 

```
  checkAvailability.test.js
    tests
      ✓ no clients
      ✓ client not supported on architecture
      ✓ client not supported on platform
      ✓ unable to resolve binary
      ✓ sanity check failed
      ✓ sanity check passed
      ✓ sanity check is mandatory
      ✓ client config returned
      ✓ search additional folders

  config.test.js
    tests
      ✓ DefaultConfig
      ✓ no config given
      ✓ config override

  download.test.js
    tests
      ✓ no clients
      ✓ client not supported on architecture
      ✓ client not supported on platform
      ✓ download info not available
      ✓ download url not available
      ✓ download unpack command not available
      ✓ download fails (53ms)
      ✓ unsupported archive type
      ✓ hash sha256 mismatch
      ✓ hash md5 mismatch
      ✓ url regex mismatch
      ✓ unpacks and verifies ok (54ms)
      ✓ unpacked but no binary found (43ms)
      ✓ unpacked but sanity check failed
      ✓ unpacked and set to required name (41ms)
      ✓ unpacked updated version and copied over old version (83ms)
      ✓ hash sha256 match (38ms)
      ✓ hash md5 match (39ms)
      custom unpack handler
        ✓ success
        ✓ fail

  logger.test.js
    tests
      ✓ nothing by default
test logging
      ✓ turn on and off
      ✓ must be valid logger


  35 passing (3s)
```
